pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "TerminalApp"
include ':app'
include ':termux-emulator'
include ':termux-view'
project(':termux-emulator').projectDir = file('termux/terminal-emulator')
project(':termux-view').projectDir = file('termux/terminal-view')
